/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 5
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 16
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_blank_line = 1,
  sym_header = 2,
  sym_summary_line = 3,
  sym_section_header = 4,
  sym_edge_line = 5,
  sym_ref_line = 6,
  sym_symbol_line = 7,
  sym_comment = 8,
  sym_kv_line = 9,
  sym_inline_array = 10,
  sym_nested_field = 11,
  sym_tabular_row = 12,
  sym_source_file = 13,
  sym__line = 14,
  aux_sym_source_file_repeat1 = 15,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_blank_line] = "blank_line",
  [sym_header] = "header",
  [sym_summary_line] = "summary_line",
  [sym_section_header] = "section_header",
  [sym_edge_line] = "edge_line",
  [sym_ref_line] = "ref_line",
  [sym_symbol_line] = "symbol_line",
  [sym_comment] = "comment",
  [sym_kv_line] = "kv_line",
  [sym_inline_array] = "inline_array",
  [sym_nested_field] = "nested_field",
  [sym_tabular_row] = "tabular_row",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_blank_line] = sym_blank_line,
  [sym_header] = sym_header,
  [sym_summary_line] = sym_summary_line,
  [sym_section_header] = sym_section_header,
  [sym_edge_line] = sym_edge_line,
  [sym_ref_line] = sym_ref_line,
  [sym_symbol_line] = sym_symbol_line,
  [sym_comment] = sym_comment,
  [sym_kv_line] = sym_kv_line,
  [sym_inline_array] = sym_inline_array,
  [sym_nested_field] = sym_nested_field,
  [sym_tabular_row] = sym_tabular_row,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_summary_line] = {
    .visible = true,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_edge_line] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_line] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_kv_line] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_array] = {
    .visible = true,
    .named = true,
  },
  [sym_nested_field] = {
    .visible = true,
    .named = true,
  },
  [sym_tabular_row] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(70);
      ADVANCE_MAP(
        '\n', 71,
        '\r', 1,
        '#', 48,
        '.', 64,
        '@', 61,
        'G', 55,
        '|', 3,
        '\t', 2,
        0x0b, 2,
        '\f', 2,
        ' ', 2,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(71);
      if (lookahead == '.') ADVANCE(64);
      if (lookahead == '|') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '.') ADVANCE(64);
      if (lookahead == '|') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(82);
      if (lookahead == '|') ADVANCE(3);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(78);
      if (lookahead == '|') ADVANCE(4);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(81);
      if (lookahead == '|') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(5);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(79);
      if (lookahead == '|') ADVANCE(7);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == 'a') ADVANCE(11);
      if (lookahead == '|') ADVANCE(15);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == 'm') ADVANCE(8);
      if (lookahead == '|') ADVANCE(15);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == 'm') ADVANCE(9);
      if (lookahead == '|') ADVANCE(15);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == 'r') ADVANCE(14);
      if (lookahead == '|') ADVANCE(15);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == 's') ADVANCE(13);
      if (lookahead == '|') ADVANCE(15);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == 'u') ADVANCE(10);
      if (lookahead == '|') ADVANCE(15);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == 'y') ADVANCE(44);
      if (lookahead == '|') ADVANCE(15);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 15:
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == '|') ADVANCE(15);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 16:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == ' ') ADVANCE(29);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 17:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == ' ') ADVANCE(35);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 18:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 19:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 'a') ADVANCE(27);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 20:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 'd') ADVANCE(45);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 21:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 'e') ADVANCE(38);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 22:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 'e') ADVANCE(20);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 23:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 'i') ADVANCE(28);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 24:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 'i') ADVANCE(36);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 25:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 'l') ADVANCE(39);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 26:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 'm') ADVANCE(24);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 27:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 'n') ADVANCE(33);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 28:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 'o') ADVANCE(37);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 29:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 'p') ADVANCE(30);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 30:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 'r') ADVANCE(21);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 31:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 'r') ADVANCE(19);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 32:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 's') ADVANCE(25);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 33:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 's') ADVANCE(26);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 34:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 't') ADVANCE(22);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 35:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 36:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 't') ADVANCE(34);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 37:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 'u') ADVANCE(32);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 38:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 'v') ADVANCE(23);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 39:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == 'y') ADVANCE(17);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 40:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 41:
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '|') ADVANCE(41);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 42:
      if (lookahead == '\n') ADVANCE(75);
      if (lookahead == '|') ADVANCE(42);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 43:
      if (lookahead == '\n') ADVANCE(80);
      if (lookahead == '|') ADVANCE(43);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 44:
      if (lookahead == '\n') ADVANCE(73);
      if (lookahead == '|') ADVANCE(44);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 45:
      if (lookahead == '\n') ADVANCE(76);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 46:
      if (lookahead == ' ') ADVANCE(60);
      if (lookahead == '|') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 47:
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == '|') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 48:
      if (lookahead == ' ') ADVANCE(4);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == '|') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 49:
      if (lookahead == ' ') ADVANCE(66);
      if (lookahead == '=') ADVANCE(7);
      if (lookahead == '[') ADVANCE(62);
      if (lookahead == '|') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 50:
      if (lookahead == ' ') ADVANCE(47);
      if (lookahead == '<') ADVANCE(58);
      if (lookahead == '|') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 51:
      if (lookahead == ' ') ADVANCE(67);
      if (lookahead == '|') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 52:
      if (lookahead == ' ') ADVANCE(68);
      if (lookahead == '|') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 53:
      if (lookahead == '.') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(53);
      END_STATE();
    case 54:
      if (lookahead == ':') ADVANCE(52);
      if (lookahead == '|') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 55:
      if (lookahead == '=') ADVANCE(7);
      if (lookahead == 'C') ADVANCE(56);
      if (lookahead == '[') ADVANCE(62);
      if (lookahead == '|') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 56:
      if (lookahead == '=') ADVANCE(7);
      if (lookahead == 'F') ADVANCE(49);
      if (lookahead == '[') ADVANCE(62);
      if (lookahead == '|') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 57:
      if (lookahead == '=') ADVANCE(7);
      if (lookahead == '[') ADVANCE(62);
      if (lookahead == '|') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 58:
      if (lookahead == '@') ADVANCE(63);
      if (lookahead == '|') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 59:
      if (lookahead == ']') ADVANCE(54);
      if (lookahead == '|') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 60:
      if (lookahead == '_') ADVANCE(12);
      if (lookahead == '|') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(15);
      END_STATE();
    case 61:
      if (lookahead == '|') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 62:
      if (lookahead == '|') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 63:
      if (lookahead == '|') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 64:
      if (lookahead == '|') ADVANCE(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 65:
      if (lookahead == '|') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 66:
      if (lookahead == '|') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 67:
      if (lookahead == '|') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 68:
      if (lookahead == '|') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 69:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_blank_line);
      if (lookahead == '.') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(53);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_header);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_summary_line);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_section_header);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_edge_line);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_ref_line);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_symbol_line);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_kv_line);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_inline_array);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_nested_field);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_tabular_row);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_blank_line] = ACTIONS(1),
    [sym_header] = ACTIONS(1),
    [sym_summary_line] = ACTIONS(1),
    [sym_section_header] = ACTIONS(1),
    [sym_edge_line] = ACTIONS(1),
    [sym_ref_line] = ACTIONS(1),
    [sym_symbol_line] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_kv_line] = ACTIONS(1),
    [sym_inline_array] = ACTIONS(1),
    [sym_nested_field] = ACTIONS(1),
    [sym_tabular_row] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(4),
    [sym__line] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_blank_line] = ACTIONS(5),
    [sym_header] = ACTIONS(7),
    [sym_summary_line] = ACTIONS(7),
    [sym_section_header] = ACTIONS(5),
    [sym_edge_line] = ACTIONS(7),
    [sym_ref_line] = ACTIONS(7),
    [sym_symbol_line] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [sym_kv_line] = ACTIONS(7),
    [sym_inline_array] = ACTIONS(7),
    [sym_nested_field] = ACTIONS(7),
    [sym_tabular_row] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__line] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(9),
    [sym_blank_line] = ACTIONS(11),
    [sym_header] = ACTIONS(13),
    [sym_summary_line] = ACTIONS(13),
    [sym_section_header] = ACTIONS(11),
    [sym_edge_line] = ACTIONS(13),
    [sym_ref_line] = ACTIONS(13),
    [sym_symbol_line] = ACTIONS(11),
    [sym_comment] = ACTIONS(13),
    [sym_kv_line] = ACTIONS(13),
    [sym_inline_array] = ACTIONS(13),
    [sym_nested_field] = ACTIONS(13),
    [sym_tabular_row] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym__line] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_blank_line] = ACTIONS(17),
    [sym_header] = ACTIONS(20),
    [sym_summary_line] = ACTIONS(20),
    [sym_section_header] = ACTIONS(17),
    [sym_edge_line] = ACTIONS(20),
    [sym_ref_line] = ACTIONS(20),
    [sym_symbol_line] = ACTIONS(17),
    [sym_comment] = ACTIONS(20),
    [sym_kv_line] = ACTIONS(20),
    [sym_inline_array] = ACTIONS(20),
    [sym_nested_field] = ACTIONS(20),
    [sym_tabular_row] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [23] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gcf(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gcf",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
